# Docker compose to build and run the eureka service
version: '3'
services:
  hello-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5010:8080"

networks:
  default:
    external:
      name: springboot